
/** TODO here we need just to check functions
 * [] generateId() return correct size
 * []   we can parse correct date
 * []   random data not same all time
 * []   increment works as we think
 * [] setChunkMetaInfo() writes data at correct position and that data is correct
 * [] parseId() throws error for non correct id size
 * []   date is correct
 * []   id size correct
 * []   total expected
 * []   index expected
 * [] id generated by generateId and setChunkMetaInfo correctly parsed by parseId
*/
